print("¡Hola Mundo!")
print("La Witsi Witsi Araña\nsubió a su telaraña.")
print()
print("Vino la lluvia\ny se la llevó.")
print("\\")
print("La Witsi Witsi Araña" , "subió" , "a su telaraña.")
print("Mi nombre es", "Python.")
print("Monty Python.")
print("Mi nombre es", "Python.", end="    ")
print("Monty Python.")
print("Mi", "nombre", "es", "Monty", "Python.", sep="-")
print("Mi", "nombre", "es", sep="_", end="*")
print("Monty", "Python.", sep="*", end="*\n")
